services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - default
      - dev-proxy
    environment:
      - ADDR=:8080
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-greenlight}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-greenlight}
    volumes:
      - api-postgres:/var/lib/postgresql/data
      - ./docker/db/data/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "54322:5432"

volumes:
  api-postgres:

networks:
  default:
  dev-proxy:
    external: true