FROM golang:alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY . .
RUN go mod download

RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
